@startuml
!include .\\Common\Context.puml
!include .\\Common\EnvironmentalSettings.puml
!include .\\Common\FileExtensions.puml
!include .\\Common\Logging.puml
!include .\\Common\Measurer.puml
!include .\\Common\PresetsService.puml
!include .\\Compatibility\AudioCodecsCompatibility.puml
!include .\\Compatibility\ContainerFormatCompatibility.puml
!include .\\Compatibility\VideoCodecsCompatibility.puml
!include .\\Compatibility\VideoResolutionCompatibility.puml
!include .\\Conversion\AbstractConverter.puml
!include .\\Conversion\AudioConverter.puml
!include .\\Conversion\FfmpegArgs.puml
!include .\\Conversion\FfmpegMetadata.puml
!include .\\Conversion\ImageConverter.puml
!include .\\Conversion\VideoConverter.puml
!include .\\Endpoint\ConversionValidator.puml
!include .\\Endpoint\Endpoint.puml
!include .\\Enums\EnvironmentType.puml
!include .\\Enums\GPUType.puml
!include .\\Enums\HardwareAcceleration.puml
!include .\\Enums\InputOptions.puml
!include .\\Enums\InterfaceType.puml
!include .\\Enums\MessageType.puml
!include .\\Interfaces\IDisplay.puml
!include .\\Parsers\NumberParser.puml
!include .\\Parsers\TimeParser.puml
!include .\\Common\Configuration\BackendConfig.puml
!include .\\Common\Configuration\HardwareConfig.puml
!include .\\Common\Configuration\InterfaceConfig.puml
!include .\\Common\Options\AudioOptions.puml
!include .\\Common\Options\EndpointOptions.puml
!include .\\Common\Options\FileOptions.puml
!include .\\Common\Options\ImageOptions.puml
!include .\\Common\Options\VideoOptions.puml
!include .\\Common\Setup\DependencySetup.puml
!include .\\Common\Setup\HardwareDetection.puml
!include .\\Common\Shared\EnvironmentPathes.puml
!include .\\Common\Shared\PathInfo.puml
!include .\\Common\Shared\Preset.puml
!include .\\Common\Shared\TestingEnvironment.puml
!include .\\Enums\Attributes\AudioCodecAttribute.puml
!include .\\Enums\Attributes\ContainerFormatAttribute.puml
!include .\\Enums\Attributes\ImageEffectsAttribute.puml
!include .\\Enums\Attributes\ImageFormatAttribute.puml
!include .\\Enums\Attributes\NameAttribute.puml
!include .\\Enums\Attributes\ResolutionAttribute.puml
!include .\\Enums\Attributes\VideoCodecAttribute.puml
!include .\\Enums\AudioVideo\AudioBitRate.puml
!include .\\Enums\AudioVideo\AudioCodecs.puml
!include .\\Enums\AudioVideo\ContainerFormat.puml
!include .\\Enums\AudioVideo\Resolutions.puml
!include .\\Enums\AudioVideo\SamplingFrequency.puml
!include .\\Enums\AudioVideo\VideoCodecs.puml
!include .\\Enums\Helpers\AudioCodecsHelper.puml
!include .\\Enums\Helpers\ContainerFormatHelper.puml
!include .\\Enums\Helpers\ImageEffectsHelper.puml
!include .\\Enums\Helpers\ImageFormatHelper.puml
!include .\\Enums\Helpers\NameAttributeHelper.puml
!include .\\Enums\Helpers\PixelFormatHelper.puml
!include .\\Enums\Helpers\ResolutionHelper.puml
!include .\\Enums\Helpers\VideoCodecsHelper.puml
!include .\\Enums\Image\ImageEffects.puml
!include .\\Enums\Image\ImageFormat.puml
!include .\\Enums\Image\PixelFormats.puml
!include .\\Enums\Preset\PresetQuality.puml
!include .\\Enums\Preset\PresetTarget.puml
!include .\\Enums\Preset\PresetType.puml
@enduml
