@startuml
!include .puml\Backend\Common\Options\AudioOptions.puml
!include .puml\Backend\Common\Options\FileOptions.puml
!include .puml\Backend\Enums\AudioVideo\AudioBitRate.puml
!include .puml\Backend\Enums\AudioVideo\AudioCodecs.puml
!include .puml\Backend\Enums\AudioVideo\ContainerFormat.puml
!include .puml\Backend\Enums\AudioVideo\SamplingFrequency.puml
!include .puml\Backend\Enums\Attributes\AudioCodecAttribute.puml
!include .puml\Backend\Enums\Attributes\ContainerFormatAttribute.puml
@enduml